version: '3.8'

services:
  go:
    container_name: go
    build:
      context: apps/api
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    env_file: apps/api/.env
    ports:
      - 8080:8080
    volumes:
      - ./apps/api:/app
